import json
import re
from pathlib import Path

SONGS_JSON = Path.home() / "Projects/music-player/public/songs.json"

def clean_artist(artist_str):
    if not artist_str: return "Unknown Artist"
    
    # Common junk to strip
    junk_patterns = [
        r"Provided to YouTube by.*",
        r"Auto-generated by YouTube.*",
        r"℗ \d{4}.*",
        r"Released on:.*",
        r"Main Artist:.*",
        r"Producer:.*",
        r"Composer:.*"
    ]
    
    cleaned = artist_str
    for pattern in junk_patterns:
        cleaned = re.split(pattern, cleaned, flags=re.IGNORECASE)[0]
    
    # Remove separators like " · " if it looks like a list of 5+ artists
    if cleaned.count(" · ") > 2:
        cleaned = cleaned.split(" · ")[0] + " et al."
        
    return cleaned.strip().strip("-").strip()

def main():
    with open(SONGS_JSON, "r") as f:
        songs = json.load(f)
    
    updates = 0
    for song in songs:
        meta = song.get("meta", {})
        artist = meta.get("artist")
        
        if artist and (len(artist) > 40 or "Provided to" in artist):
            new_artist = clean_artist(artist)
            if new_artist != artist:
                print(f"Cleaning: {artist[:30]}... -> {new_artist}")
                song["meta"]["artist"] = new_artist
                updates += 1
                
    if updates > 0:
        with open(SONGS_JSON, "w") as f:
            json.dump(songs, f, indent=2)
        print(f"\nCleaned {updates} artist names.")
    else:
        print("\nArtist names look clean.")

if __name__ == "__main__":
    main()
